[package]
name = "readnesrom"
version = "0.1.0"
authors = ["Jing Peng <pj.hades@gmail.com>"]

[dependencies]
clap = { version = "^2.33.0", default-features = false }
redwhite = { path = ".." }
sdl2 = "^0.31.0"
